//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliceDepartment
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public short Person_ID { get; set; }
        public string SocialNum { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleNames { get; set; }
        public string Photo { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string POB { get; set; }
        public Nullable<short> Eth_ID { get; set; }
        public string Build { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public Nullable<short> Hair_ID { get; set; }
        public Nullable<short> Eye_ID { get; set; }
        public string Officer { get; set; }
        public string Criminal { get; set; }
        public string Victim { get; set; }
        public Nullable<short> License_ID { get; set; }
    }
}
